name: Publish New Version
on:
  push:
    tags:
      - v*.*.*
jobs:
  publish:
    name: Build and Publish to Github
    runs-on: ubuntu-latest
    concurrency:
      group: publish
      cancel-in-progress: false
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Prepare
        id: prep-env
        run: ./data/gha-prep.sh
      - name: Build
        id: build-zip
        run: ./data/gha-build.sh
      - name: Package
        id: package-tf
        run: ./data/gha-package.sh
      - name: Publish
        uses: softprops/action-gh-release@v2
        draft: true
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref_name }}
        files: release/*
